---
title: "5206hw9a_br2498"
author: "Bo Rong   br2498"
date: "November 26, 2016"
output: pdf_document
---

```{r}
#1.
filename <- "~/Downloads/ckm_nodes-1.csv"
nodes<- read.csv(file=filename, header=T)
dim(nodes)
#(a)
nodes.a<-subset(nodes,adoption_date!="NA"&adoption_date!="Inf")
nrow(nodes.a)
#(b)
nodes.b<-subset(nodes,adoption_date=="Inf")
nrow(nodes.b)
#(c)
nodes.c<-subset(nodes,is.na(adoption_date))
nrow(nodes.c)
```

```{r}
#2.
index_num<-which(nodes$adoption_date%in%c(1:17,"Inf"))
length(index_num)
nodes<-nodes[index_num,]
```

```{r}
#3.
frq<-table(nodes$adoption_date)
t<-data.frame(frq)
plot(c(1:17,"Inf"),t$Freq ,xlab="month",ylab="numbers of doctors")
total<-NULL
for (i in 2:length(c(1:17,"Inf"))) {
  total[1]=11
  total[i]=t$Freq[i]+total[i-1]
}

plot(c(1:17,"Inf"),total ,xlab="month",ylab="total numbers of doctors")
```

```{r}
#4.
by2<-nodes$adoption_date<=2
which(by2)
af14<-nodes$adoption_date>14
which(af14)
```


```{r}
#5.
filename <- "~/Downloads/ckm_network-1.txt"
network<- read.table(file=filename, header=F)
network1<-as.matrix(network)
all(network1 %in% 0:1)
table(network1)
A<-network[index_num,index_num]
dim(A)
```


```{r}
#6.
B<-apply(data.frame(A), 1, sum)
B<-as.vector(B)
B[41]
```


```{r}
#7.
which(A[37]==1&nodes$adoption_date<=5)
length(which(A[37]==1&nodes$adoption_date<=5))/B[37]
```






























