---
title: "5206hw3_br2498"
author: Bo Rong   br2498
date: "October 8, 2016"
output: html_document
---

```{r}
#i.a.
setwd("/Users/brong/Downloads")
nets1617<-readLines("NetsSchedule.html",warn = FALSE)
length(nets1617)
#b.
sum(nchar(nets1617))
#c.
max(nchar(nets1617))
```

```{r}
#ii. 
#First game: Wed,Oct 26	play against Boston.
#last game: Wed, Apr 12 play against Chicago.
```


```{r}
#iii.
#line 315 in the file holds information about the first game of the regular season.
#line 396 provides the date, time, and opponent for the final game

```

```{r}
#iv.
capture_date_game<-"\\w{3}, \\w{3} \\d{1,2}"
grep(capture_date_game, nets1617, value=FALSE)
```

```{r}
#v.
m<-regexpr(capture_date_game,nets1617,perl=TRUE)
date<-regmatches(nets1617,m)
```

```{r}
#vi.
capture_time_game<-"(1[012]|[1-9]):[0-5][0-9](\\s)?(?i)(AM|PM)"
m<-regexpr(capture_time_game,nets1617,perl=TRUE)
time<-regmatches(nets1617,m)
```

```{r}
#vii.
capture_home_or_away<-"(game-status)"
home_grep<-grep(capture_home_or_away, nets1617, value=TRUE)
m<-regexpr("game-status",home_grep)
m_1<-regexpr("team-logo-small logo-nba-small",home_grep)
x<-substring(home_grep,m+13,m_1-17)
home<-ifelse(x=="vs",1,0)
```

```{r}
#viii.
capture_opponent<-"(</a></li></ul></td><td>)"
opponent_grep<-grep(capture_opponent, nets1617, value=TRUE)
m<-regexpr("(</a></li></ul></td><td>)",home_grep)
m1<-regexpr("(>)(\\w+)(\\s*)(\\w*)(</a></li></ul></td><td>)",home_grep)
opponent<-substring(home_grep,m1+1,m-1)
```


```{r}
#ix.
dtoh<-data.frame(date, time, opponent, home)
head(dtoh,10)
```









