---
title: "5206hw4_br2498"
author: Bo Rong   br2498
date: "October 21, 2016"
output: html_document
---

```{r}
#1.
#i.
setwd("/Users/brong/Downloads")
gmp     <- read.table("gmp.txt", header = TRUE)
gmp$pop <- round(gmp$gmp/gmp$pcgmp)
plot(gmp$pop, gmp$pcgmp, log ="x", xlab="Population",ylab="Per-capita Economic Output")
curve(6611*x^{1/8}, add = TRUE, col = "blue")
curve(6611*x^{0.1}, add = TRUE, col = "red")
curve(6611*x^{0.15}, add = TRUE, col = "green")
```

```{r}
#ii.
mse <- function(beta_,x=gmp$pop,y=gmp$pcgmp) {
  compute_mean<-(y-beta_[1]*x^beta_[2])^2
 result<-mean(compute_mean)
return(result)}
mse(c(6611, 0.15))
mse(c(5000, 0.10))
```

```{r,warning=FALSE}
#iii.
nlm(mse,c(6611,0.125))$minimum
nlm(mse,c(6611,0.1))$minimum
nlm(mse,c(6611,0.15))$minimum
#minimum is the value of the estimated minimum of mse.
nlm(mse,c(6611,0.125))$estimate
nlm(mse,c(6611,0.1))$estimate
nlm(mse,c(6611,0.15))$estimate
#estimate is the point at which the minimum value of mse is obtained.
```

```{r,warning=FALSE}
#iv.
plm<-function(beta_0,beta_1,x=gmp$pop,y=gmp$pcgmp) {
final_estimate<-nlm(mse,c(beta_0,beta_1),x,y)$estimate
final_mse<-nlm(mse,c(beta_0,beta_1),x,y)$minimum
final_estimate_mse<-list(final_estimate,final_mse)
names(final_estimate_mse) <- c("Final Beta Estimate","MSE")
return(final_estimate_mse)
}
plm(6611,0.15)
plm(5000,0.10)
#These parameter estimate are different, beacuse the initial guess for beta0 and beta1 are different. beta0=6611 and beta1=0.15 has a lower MSE.
```

```{r}
#v.
#(a)
m_pcgmp<-mean(gmp$pcgmp)
sd_pcgmp<-sd(gmp$pcgmp)
N<-nrow(gmp)
sd_error_mean<-sd_pcgmp/sqrt(N)
sd_error_mean
```

```{r}
#(b)

indices<-gmp$pcgmp
indices_mean <- function(x) {
  inm<-mean(indices[x])  
  return(inm)
}
```


```{r,warning=FALSE}
#(c)
B <- length(gmp$pcgmp)
resampled_values <- NULL
bootstrap.means<-NULL
for (c in 1:100) {
for(b in 1:B){
  resampled_values[b]<- sample(1:length(indices),B,replace=TRUE)
}
bootstrap.means[c]<-indices_mean(resampled_values)
}
```

```{r}
#(d)
sd(bootstrap.means)
#These two values are very closed.
```

```{r,warning=FALSE}
#vi.
plm.bootstrap<-function(beta_0,beta_1,x=gmp$pop,y=gmp$pcgmp,B=100){
  beta_0_bootstrap <- rep(NA,B)
  beta_1_bootstrap <- rep(NA,B)
  
  for(i in 1:B){
    set.seed(i)
resampled_values <- sample(1:length(gmp$pcgmp),length(gmp$pcgmp),replace=TRUE)
bootstrap_x <- x[resampled_values]
bootstrap_y <- y[resampled_values]
plm_bootstrap<-plm(beta_0,beta_1, x=bootstrap_x, y=bootstrap_y)
beta_0_bootstrap[i] <-unlist(plm_bootstrap)[1]
beta_1_bootstrap[i] <-unlist(plm_bootstrap)[2]
  }
  sd_beta_0=sd(beta_0_bootstrap)
  sd_beta_1=sd(beta_1_bootstrap)
  sd_error_beta <- list(sd_beta_0,sd_beta_1)
  names(sd_error_beta) <- c("sd_error_beta0", "sd_error_beta1")
  return(sd_error_beta)
}
  
  plm.bootstrap(6611,0.15)
plm.bootstrap(5000,0.10)
```



```{r,warning=FALSE}
#vii.
setwd("/Users/brong/Downloads")
gmp_2013<- read.table("gmp-2013.txt", header = TRUE)
gmp_2013$pop <- round(gmp_2013$gmp/gmp_2013$pcgmp)
plm(6611,0.15,x=gmp_2013$pop,y=gmp_2013$pcgmp)
plm(5000,0.10,x=gmp_2013$pop,y=gmp_2013$pcgmp)
plm.bootstrap(6611,0.15,x=gmp_2013$pop,y=gmp_2013$pcgmp,B=100)
plm.bootstrap(5000,0.10,x=gmp_2013$pop,y=gmp_2013$pcgmp,B=100)
#The estimate of beta1 changed significantly.
```







