---
title: "HW 1"
author: "Bo Rong br2498"
date: "September 25, 2016"
output: html_document
---
```{r}
#Part 1
#i.
filename <- "~/Downloads/Titanic.txt"
titanic<-read.table(file = filename,as.is = TRUE,header = TRUE)
```

```{r}
#ii.
c(nrow(titanic),ncol(titanic))
```

```{r}
#iii.
Survived.Word<-read.table(file=filename,header = TRUE)[ 'Survived']
Survived.Word$Survived[Survived.Word$Survived == 1]<-'survived'
Survived.Word$Survived[Survived.Word$Survived == 0]<- 'died'
Survived_word_added<-cbind(titanic,Survived.Word)
```


```{r}
#part 2
#i.
Survived_Age_Fare<-read.table(file=filename,header = TRUE)[ ,c('Survived', 'Age','Fare')]
apply(Survived_Age_Fare,2,mean)
#The mean value of Survived is 0.3838384 means 38.38384% of passengers survived.
#The mean of Age is NA,because there is missing value in Age.
```

```{r}
#ii.
Survived_female<-subset(titanic,Survived==1&Sex=='female')
nrow(Survived_female)
round(nrow(Survived_female)/nrow(titanic),digits=2)
```

```{r}
#iii.
survivors<-subset(titanic,Survived==1)
round(nrow(Survived_female)/nrow(survivors),digits=2)
```

```{r}
#iv.
classes <- sort(unique(titanic$Pclass))
Pclass.Survival <- vector("numeric", length = 3)
names(Pclass.Survival) <- classes
for (i in 1:3) {
Pclass.Survival[i]<-round(nrow(subset(titanic,Survived==1&Pclass==i))/nrow(subset(titanic,Pclass==i)),digits=2)
}
print(Pclass.Survival)
```

```{r}
s <- tapply(titanic$Survived, titanic$Pclass, sum)
l <- tapply(titanic$Survived, titanic$Pclass, length)
Pclass.Survival2 <- round(s/l, digits = 2)
Pclass.Survival2  
```

```{r}
#Yes, based on the previous question,there is a relationship between survival rate and class.
#First class passengers have the highest survial rate,followed by the second class.
#The third class has the lowest survival rate.
```








