---
title: "Midterm Section 5206hybrid"
author: "Bo Rong br2498"
date: "October 21, 2016"
output: html_document
---

```{r}
#Question1
#(a)
setwd("/Users/brong/Downloads")
rich<-readLines("rich.html",warn = FALSE)
filename <- "~/Downloads/rich_dataframe-1.txt"
rich_df<-read.table(file = filename,as.is = TRUE,header = TRUE)
```

```{r}
#(b)
worth_lines <- grep("td class=\"worth\"", rich,value=TRUE)
m<-regexpr("td class=\"worth\"",worth_lines)
m_1<-regexpr("B</td>",worth_lines)
networths<-substring(worth_lines,m+17,m_1)
networths[1:5]
```


```{r}
#(c)
worth_lines <- grep("td class=\"worth\"", rich,value=TRUE)
m<-regexpr("td class=\"worth\"",worth_lines)
m_1<-regexpr("B</td>",worth_lines)
networthsnew<-substring(worth_lines,m+18,m_1-1)
networthsnew1<-gsub(",",".",networthsnew)
networths2<-as.numeric(networthsnew1)
```

```{r}
#(d)
MyWorth<-c(networths2)
rich_df<-cbind(rich_df,MyWorth)
head(rich_df)
```



```{r}
#Question2
#(a)
#ggplot2(data = rich_df) + geom_point(mapping = aes(x = Age, y = Networths))
```


```{r}
#(b)


```





